import { useCallback, useEffect, useState, type FormEvent } from 'react'
import type { Session } from '@supabase/supabase-js'
import { supabase } from './lib/supabase'

type Patient={id:string;full_name:string;anonymous_code:string}
type Version={id:string;version_no:number;title:string;published_at:string}
type Item={id:string;title:string;content_type:string;tags:string[];status:string;content_library_versions:Version[]}
type Brand={public_name:string;primary_color:string;logo_url:string|null}

export function ContentLibrary({ session, organizationId, patients, canEditBrand }:{session:Session;organizationId:string;patients:Patient[];canEditBrand:boolean}){
  const [items,setItems]=useState<Item[]>([]),[brand,setBrand]=useState<Brand|null>(null),[message,setMessage]=useState('')
  const load=useCallback(async()=>{const [itemsResult,brandResult]=await Promise.all([supabase.from('content_library_items').select('id,title,content_type,tags,status,content_library_versions(id,version_no,title,published_at)').eq('organization_id',organizationId).order('updated_at',{ascending:false}),supabase.from('organization_branding').select('public_name,primary_color,logo_url').eq('organization_id',organizationId).order('updated_at',{ascending:false})]);if(itemsResult.error||brandResult.error)setMessage(itemsResult.error?.message??brandResult.error?.message??'Não foi possível carregar a biblioteca.');else{setItems((itemsResult.data??[]) as Item[]);setBrand(((brandResult.data??[]) as Brand[])[0]??null)}},[organizationId])
  useEffect(()=>{void load()},[load])
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),title=String(data.get('title')).trim(),body=String(data.get('body')).trim();const item=await supabase.from('content_library_items').insert({organization_id:organizationId,title,content_type:String(data.get('type')),tags:String(data.get('tags')).split(',').map(tag=>tag.trim()).filter(Boolean),created_by:session.user.id}).select('id').single();if(item.error||!item.data)return setMessage(item.error?.message??'Não foi possível criar o conteúdo.');const {error}=await supabase.rpc('publish_content_library_version',{target_item_id:item.data.id,target_body:body});if(error)setMessage(error.message);else{event.currentTarget.reset();setMessage('Conteúdo publicado como versão imutável.');await load()}}
  async function deliver(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),{error}=await supabase.rpc('deliver_content_to_patient',{target_version_id:String(data.get('version')),target_patient_id:String(data.get('patient'))});if(error)setMessage(error.message);else setMessage('Conteúdo entregue ao paciente como cópia.');}
  async function saveBrand(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),{error}=await supabase.from('organization_branding').upsert({organization_id:organizationId,public_name:String(data.get('publicName')),primary_color:String(data.get('primaryColor')),logo_url:String(data.get('logoUrl'))||null,updated_by:session.user.id},{onConflict:'organization_id'});if(error)setMessage(error.message);else{setMessage('Marca da clínica atualizada.');await load()}}
  const versions=items.flatMap(item=>item.content_library_versions.map(version=>({...version,itemTitle:item.title})))
  return <section className="content-library"><header><span className="eyebrow">Biblioteca da clínica</span><h2>Orientações reutilizáveis</h2><p>O que chega ao paciente é uma cópia da versão publicada.</p></header>{message&&<p className="notice" role="status">{message}</p>}{canEditBrand&&<section className="panel brand-settings"><h2>Marca da clínica</h2><form onSubmit={saveBrand}><label>Nome público<input name="publicName" defaultValue={brand?.public_name??''} required maxLength={120}/></label><label>Cor primária<input name="primaryColor" type="color" defaultValue={brand?.primary_color??'#3e6b5c'}/></label><label>URL do logo<input name="logoUrl" type="url" defaultValue={brand?.logo_url??''}/></label><button className="secondary">Salvar marca</button></form></section>}<div className="library-grid"><section className="panel"><h2>Novo conteúdo</h2><form onSubmit={create}><label>Título<input name="title" required maxLength={160}/></label><label>Tipo<select name="type"><option value="guidance">Orientação</option><option value="recipe">Receita</option><option value="education">Material educativo</option><option value="protocol">Protocolo interno</option></select></label><label>Tags<input name="tags" placeholder="Ex.: café, fibras, rotina"/></label><label>Conteúdo<textarea name="body" required maxLength={12000}/></label><button className="primary">Publicar versão</button></form></section><section className="panel"><h2>Entregar ao paciente</h2><form onSubmit={deliver}><label>Paciente<select name="patient" required><option value="">Selecione</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{patient.anonymous_code} · {patient.full_name}</option>)}</select></label><label>Versão publicada<select name="version" required><option value="">Selecione</option>{versions.map(version=><option key={version.id} value={version.id}>{version.itemTitle} · v{version.version_no}</option>)}</select></label><button className="secondary">Entregar cópia</button></form></section></div><section className="panel library-list"><h2>Conteúdos publicados</h2>{items.length?items.map(item=><article key={item.id}><span className="catalog-badge">{item.content_type}</span><strong>{item.title}</strong><small>{item.tags.join(' · ')||'Sem tags'} · {item.content_library_versions.length} versão(ões)</small></article>):<p className="muted">Nenhum conteúdo criado.</p>}</section></section>
}
