import { useEffect, useMemo, useState } from 'react'
import { Search } from 'lucide-react'

type Exercise = {
  id: string; name: string; category: string; equipment: string; target: string; muscle_group: string
  secondary_muscles: string[]; instruction_steps: Record<string, string[]>
}

export function ExerciseWorkspace() {
  const [exercises, setExercises] = useState<Exercise[]>([]), [query, setQuery] = useState(''), [category, setCategory] = useState(''), [selected, setSelected] = useState<Exercise | null>(null), [error, setError] = useState('')
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}data/exercises.json`).then(r => r.ok ? r.json() : Promise.reject(new Error('Falha ao carregar o catálogo.'))).then(setExercises).catch(e => setError(e.message)) }, [])
  const categories = useMemo(() => [...new Set(exercises.map(item => item.category))].sort(), [exercises])
  const shown = useMemo(() => exercises.filter(item => (!category || item.category === category) && `${item.name} ${item.equipment} ${item.target} ${item.muscle_group}`.toLowerCase().includes(query.toLowerCase())).slice(0, 60), [exercises, query, category])
  return <section className="exercise-workspace"><header><div><small>Catálogo local</small><h2>Exercícios</h2><p>1.324 exercícios com orientações técnicas. Vídeos próprios ou licenciados poderão ser associados depois.</p></div></header>{error && <p className="form-message">{error}</p>}<div className="exercise-filters"><div className="search"><Search/><input aria-label="Buscar exercícios" placeholder="Buscar por exercício, músculo ou equipamento" value={query} onChange={e => setQuery(e.target.value)}/></div><select aria-label="Filtrar por categoria" value={category} onChange={e => setCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(item => <option key={item} value={item}>{item}</option>)}</select></div>{!exercises.length && !error ? <p className="muted">Carregando catálogo...</p> : <div className="exercise-layout"><div className="exercise-list">{shown.map(item => <button className={selected?.id === item.id ? 'active' : ''} key={item.id} onClick={() => setSelected(item)}><strong>{item.name}</strong><small>{item.category} · {item.equipment} · {item.target}</small></button>)}{exercises.length > shown.length && <p className="muted">Mostrando os primeiros 60 resultados. Refine a busca para encontrar mais exercícios.</p>}</div><aside className="panel exercise-detail">{selected ? <><small>{selected.category} · {selected.equipment}</small><h3>{selected.name}</h3><p><strong>Alvo:</strong> {selected.target}</p><p><strong>Grupo muscular:</strong> {selected.muscle_group}</p><ol>{(selected.instruction_steps.en ?? []).map(step => <li key={step}>{step}</li>)}</ol></> : <p className="muted">Selecione um exercício para ver as orientações.</p>}</aside></div>}<p className="exercise-source">Dados e instruções: <a href="https://github.com/hasaneyldrm/exercises-dataset" target="_blank" rel="noreferrer">hasaneyldrm/exercises-dataset</a>, licença MIT. Mídias do repositório original não foram importadas.</p></section>
}
