import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import type { Session } from '@supabase/supabase-js'
import { ChevronRight, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { emptyNutrients, totalDay, type Meal, type NutrientKey, type Nutrients } from './lib/nutrition'
import { assistantLabels, assistantSteps, canPublishPlan, canReviewPlan, completeAssistantStep, initialAssistantState, type PlanAssistantState, type PlanAssistantStep } from './lib/planAssistant'
import { supabase } from './lib/supabase'
import { mapDraftRows, type DraftSummary, type EditorDay, type PlanRow } from './lib/planDrafts'

type Patient = { id: string; anonymous_code: string; full_name: string }
type NutrientRow = { id: string; code: string; name: string; unit: string }
type FoodRow = { id: string; name: string; preparation_state: string; food_nutrient_values: { amount_per_100g: number; nutrients: NutrientRow | null }[] }
type CatalogFood = { id: string; name: string; preparationState: string; nutrients: Nutrients }

const aliases: Record<NutrientKey, string[]> = { energyKcal: ['energy_kcal','energy','kcal'], proteinG: ['protein_g','protein'], carbohydrateG: ['carbohydrate_g','carbohydrate','carbs'], fatG: ['fat_g','fat','lipids'], fiberG: ['fiber_g','fiber'], sodiumMg: ['sodium_mg','sodium'], calciumMg: ['calcium_mg','calcium'], ironMg: ['iron_mg','iron'], potassiumMg: ['potassium_mg','potassium'], vitaminCMg: ['vitamin_c_mg','vitamin_c'] }
const keys: NutrientKey[] = ['energyKcal','proteinG','carbohydrateG','fatG']
const labels: Record<NutrientKey,string> = { energyKcal:'Energia',proteinG:'Proteína',carbohydrateG:'Carboidrato',fatG:'Gordura',fiberG:'Fibra',sodiumMg:'Sódio',calciumMg:'Cálcio',ironMg:'Ferro',potassiumMg:'Potássio',vitaminCMg:'Vitamina C' }
const initialDay = (): EditorDay => ({ id:crypto.randomUUID(), label:'Dia 1', kind:'standard', meals:[{id:crypto.randomUUID(),name:'Café da manhã',items:[]}] })

function normalize(row: FoodRow): CatalogFood {
  const nutrients=emptyNutrients()
  for(const value of row.food_nutrient_values??[]){const code=value.nutrients?.code.toLowerCase();const key=(Object.keys(aliases) as NutrientKey[]).find(k=>code&&aliases[k].includes(code));if(key)nutrients[key]=Number(value.amount_per_100g)}
  return{id:row.id,name:row.name,preparationState:row.preparation_state,nutrients}
}

export function NutritionWorkspace({session,organizationId,patients}:{session:Session;organizationId:string;patients:Patient[]}){
  const [tab,setTab]=useState<'catalog'|'plan'>('catalog')
  const [foods,setFoods]=useState<CatalogFood[]>([]),[nutrients,setNutrients]=useState<NutrientRow[]>([])
  const [days,setDays]=useState<EditorDay[]>([initialDay()]),[activeDay,setActiveDay]=useState(0)
  const [drafts,setDrafts]=useState<DraftSummary[]>([]),[loadedDraft,setLoadedDraft]=useState<string|null>(null),[loadingDrafts,setLoadingDrafts]=useState(true)
  const [loadedVersion,setLoadedVersion]=useState(''),[planStatus,setPlanStatus]=useState('draft'),[locked,setLocked]=useState(false)
  const [targets,setTargets]=useState<Record<string,number>>({energyKcal:0,proteinG:0,carbohydrateG:0,fatG:0,fiberG:0})
  const [assistant,setAssistant]=useState<PlanAssistantState>(initialAssistantState())
  const [patientId,setPatientId]=useState(''),[title,setTitle]=useState('Plano alimentar'),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const meals=days[activeDay]?.meals??[]
  const setMeals:React.Dispatch<React.SetStateAction<Meal[]>>=update=>setDays(all=>all.map((day,index)=>index===activeDay?{...day,meals:typeof update==='function'?update(day.meals):update}:day))
  const totals=useMemo(()=>totalDay(days[activeDay]?.meals??[]),[days,activeDay])

  const loadDrafts=useCallback(async()=>{
    setLoadingDrafts(true)
    const result=await supabase.from('plans').select('id,patient_id,title,status,updated_at,plan_versions(id,version_no,targets,assistant_state,locked_at,plan_days(id,label,kind,day_index,meals(id,label,position,meal_items(id,description,grams,nutrient_snapshot))))').eq('organization_id',organizationId).order('updated_at',{ascending:false})
    if(result.error){setMessage(result.error.message);setDrafts([])}else setDrafts(mapDraftRows((result.data??[]) as unknown as PlanRow[]))
    setLoadingDrafts(false)
  },[organizationId])
  const load=useCallback(async()=>{const [f,n]=await Promise.all([supabase.from('foods').select('id,name,preparation_state,food_nutrient_values(amount_per_100g,nutrients(id,code,name,unit))').eq('organization_id',organizationId).eq('is_active',true).order('name'),supabase.from('nutrients').select('id,code,name,unit').order('sort_order')]);if(f.error||n.error)setMessage(f.error?.message??n.error?.message??'Erro ao carregar catálogo.');else{setFoods(((f.data??[]) as unknown as FoodRow[]).map(normalize));setNutrients(n.data??[])}},[organizationId])
  useEffect(()=>{void Promise.all([load(),loadDrafts()])},[load,loadDrafts])

  function openDraft(draft:DraftSummary){setPatientId(draft.patientId);setTitle(draft.title);setDays(draft.days.length?draft.days:[initialDay()]);setActiveDay(0);setLoadedDraft(draft.id);setLoadedVersion(draft.versionId);setPlanStatus(draft.status);setLocked(draft.locked);setAssistant(draft.assistantState);setTargets(current=>({...current,...draft.targets}));setTab('plan');setMessage(draft.locked?'Plano publicado aberto em modo somente leitura.':`Plano aberto, versão ${draft.version}.`)}
  async function review(){if(!loadedDraft||!loadedVersion)return setMessage('Salve e abra um plano antes de revisar.');const nextAssistant=completeAssistantStep(assistant,'review');if(!canReviewPlan(assistant))return setMessage('Conclua objetivo, metas, refeições e equivalentes antes de revisar.');setBusy(true);const {error}=await supabase.rpc('review_plan_version',{target_plan_id:loadedDraft,target_version_id:loadedVersion,target_targets:targets,target_assistant_state:nextAssistant});setBusy(false);if(error)return setMessage(`Não foi possível revisar: ${error.message}`);setAssistant(nextAssistant);setPlanStatus('reviewed');setMessage('Versão revisada. Confira e publique quando estiver pronta.');await loadDrafts()}
  async function publish(){if(!loadedDraft||!loadedVersion)return setMessage('Abra uma versão revisada antes de publicar.');if(!canPublishPlan(assistant,planStatus))return setMessage('Conclua a revisão do assistente antes de publicar.');setBusy(true);const {error}=await supabase.rpc('publish_plan_version',{target_plan_id:loadedDraft,target_version_id:loadedVersion});setBusy(false);if(error)return setMessage(`Não foi possível publicar: ${error.message}`);setPlanStatus('published');setLocked(true);setAssistant(completeAssistantStep(assistant,'publish'));setMessage('Plano publicado e bloqueado para edição.');await loadDrafts()}
  function addItem(mealId:string,foodId:string,grams:number){const food=foods.find(f=>f.id===foodId);if(!food||grams<=0||!Number.isFinite(grams))return setMessage('Selecione alimento e gramas válidos.');setMeals(all=>all.map(m=>m.id===mealId?{...m,items:[...m.items,{id:crypto.randomUUID(),name:food.name,grams,nutrientsPer100g:food.nutrients}]}:m));setMessage('')}
  async function addFood(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=event.currentTarget,data=new FormData(form),values=Object.fromEntries(keys.map(k=>[k,Number(String(data.get(k)).replace(',','.'))])) as Record<NutrientKey,number>;if(keys.some(k=>!Number.isFinite(values[k])||values[k]<0)){setBusy(false);return setMessage('Informe valores válidos e não negativos.')}const result=await supabase.from('foods').insert({organization_id:organizationId,name:String(data.get('name')).trim(),preparation_state:String(data.get('state')).trim()||'unspecified',created_by:session.user.id}).select('id').single();if(result.error||!result.data){setBusy(false);return setMessage(result.error?.message??'Falha no cadastro.')}const mapped=keys.map(key=>({key,nutrient:nutrients.find(n=>aliases[key].includes(n.code.toLowerCase()))}));if(mapped.some(x=>!x.nutrient)){await supabase.from('foods').update({is_active:false}).eq('id',result.data.id);setBusy(false);return setMessage('Nutrientes principais ausentes na base. Cadastro revertido.')}const inserted=await supabase.from('food_nutrient_values').insert(mapped.map(x=>({food_id:result.data.id,nutrient_id:x.nutrient!.id,amount_per_100g:values[x.key],data_version:'custom-v1'})));if(inserted.error){await supabase.from('foods').update({is_active:false}).eq('id',result.data.id);setMessage(`Cadastro revertido: ${inserted.error.message}`)}else{form.reset();await load();setMessage('Alimento cadastrado.')}setBusy(false)}
  async function save(){
    if(!patientId||!days.length||days.some(day=>!day.meals.length))return setMessage('Escolha o paciente e mantenha ao menos uma refeição em cada dia.')
    setBusy(true);setMessage('');let planId='';const cleanup:{table:string;id:string}[]=[]
    try{
      const p=await supabase.from('plans').insert({organization_id:organizationId,patient_id:patientId,created_by:session.user.id,title:title.trim()||'Plano alimentar',status:'draft'}).select('id').single();if(p.error||!p.data)throw p.error??new Error('Falha no plano');planId=p.data.id
      const v=await supabase.from('plan_versions').insert({organization_id:organizationId,plan_id:planId,version_no:1,created_by:session.user.id,change_summary:loadedDraft?'Cópia editada de rascunho':'Versão inicial',assistant_state:assistant}).select('id').single();if(v.error||!v.data)throw v.error??new Error('Falha na versão');cleanup.push({table:'plan_versions',id:v.data.id})
      for(const [dayIndex,day] of days.entries()){
        const d=await supabase.from('plan_days').insert({organization_id:organizationId,plan_version_id:v.data.id,day_index:dayIndex,label:day.label,kind:day.kind}).select('id').single();if(d.error||!d.data)throw d.error??new Error('Falha no dia');cleanup.push({table:'plan_days',id:d.data.id})
        for(const [position,meal] of day.meals.entries()){
          const m=await supabase.from('meals').insert({organization_id:organizationId,plan_day_id:d.data.id,position,label:meal.name}).select('id').single();if(m.error||!m.data)throw m.error??new Error('Falha na refeição');cleanup.push({table:'meals',id:m.data.id})
          if(meal.items.length){const items=await supabase.from('meal_items').insert(meal.items.map((item,i)=>({organization_id:organizationId,meal_id:m.data.id,position:i,food_id:foods.find(f=>f.name===item.name)?.id,description:item.name,quantity:item.grams,unit:'g',grams:item.grams,nutrient_snapshot:item.nutrientsPer100g})));if(items.error)throw items.error}
        }
      }
      setMessage('Plano salvo como novo rascunho, versão 1.');setDays([initialDay()]);setActiveDay(0);setLoadedDraft(null);setLoadedVersion('');setPlanStatus('draft');setLocked(false);setAssistant(initialAssistantState());await loadDrafts()
    }catch(error){for(const row of cleanup.reverse())await supabase.from(row.table).delete().eq('id',row.id);if(planId)await supabase.from('plans').update({status:'archived',title:`[Falha revertida] ${title}`}).eq('id',planId);setMessage(`Falha revertida. ${error instanceof Error?error.message:''}`)}finally{setBusy(false)}
  }

  return <section className="nutrition-workspace">
    <div className="section-tabs"><button className={tab==='catalog'?'active':''} onClick={()=>setTab('catalog')}>Catálogo próprio</button><button className={tab==='plan'?'active':''} onClick={()=>setTab('plan')}>Editor de plano</button></div>
    {message&&<div className="notice" role="status">{message}</div>}
    {tab==='catalog'?<Catalog foods={foods} keys={keys} labels={labels} busy={busy} addFood={addFood}/>:<div className="plans-layout">
      <aside className="draft-panel panel"><header><div><h2>Planos</h2><small>{drafts.length} plano(s)</small></div><button aria-label="Atualizar planos" onClick={()=>void loadDrafts()}><RefreshCw/></button></header>{loadingDrafts?<p className="muted">Carregando planos...</p>:<div className="draft-list">{drafts.map(draft=><button className={loadedDraft===draft.id?'active':''} key={draft.id} onClick={()=>openDraft(draft)}><span><strong>{draft.title}</strong><small>{patients.find(p=>p.id===draft.patientId)?.full_name??'Paciente'} · {draft.days.length} dia(s) · v{draft.version}</small><time><b className={`plan-status ${draft.status}`}>{draft.status==='published'?'Publicado':draft.status==='reviewed'?'Revisado':'Rascunho'}</b> · {new Date(draft.updatedAt).toLocaleDateString('pt-BR')}</time></span><ChevronRight/></button>)}{!drafts.length&&<p className="muted">Nenhum plano salvo.</p>}</div>}</aside>
      <div className="plan-editor"><PlanAssistant state={assistant} setState={setAssistant} locked={locked}/><section className="panel plan-basics"><label>Paciente<select value={patientId} disabled={locked} onChange={e=>setPatientId(e.target.value)}><option value="">Selecione</option>{patients.map(p=><option key={p.id} value={p.id}>{p.anonymous_code} · {p.full_name}</option>)}</select></label><label>Título<input value={title} readOnly={locked} onChange={e=>setTitle(e.target.value)}/></label></section>
        <section className="panel target-panel"><header><div><h2>Metas nutricionais</h2><small>Status: {planStatus==='published'?'Publicado':planStatus==='reviewed'?'Revisado':'Rascunho'}</small></div></header><div>{[['energyKcal','Energia (kcal)'],['proteinG','Proteína (g)'],['carbohydrateG','Carboidrato (g)'],['fatG','Gordura (g)'],['fiberG','Fibra (g)']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="0.1" value={targets[key]??0} disabled={locked} onChange={e=>setTargets(all=>({...all,[key]:Number(e.target.value)}))}/></label>)}</div></section>
        <div className="day-tabs" role="tablist" aria-label="Dias do plano">{days.map((day,index)=><button role="tab" aria-selected={activeDay===index} className={activeDay===index?'active':''} key={day.id} onClick={()=>setActiveDay(index)}>{day.label}</button>)}{!locked&&<button onClick={()=>{setDays(all=>[...all,{...initialDay(),label:`Dia ${all.length+1}`}]);setActiveDay(days.length)}}><Plus/> Dia</button>}</div>
        <section className="live-totals">{keys.map(k=><div key={k}><small>{labels[k]}</small><strong>{totals[k].toLocaleString('pt-BR')} {k==='energyKcal'?'kcal':'g'}</strong></div>)}</section>
        {meals.map((meal,index)=><MealCard key={meal.id} meal={meal} index={index} foods={foods} setMeals={setMeals} addItem={addItem} readOnly={locked}/>)}
        {!locked&&<div className="editor-actions"><button className="secondary" onClick={()=>setMeals(m=>[...m,{id:crypto.randomUUID(),name:`Refeição ${m.length+1}`,items:[]}])}><Plus/>Adicionar refeição</button><span className="publication-actions"><button className="secondary" disabled={busy||!loadedDraft||!canReviewPlan(assistant)} onClick={()=>void review()}>Marcar como revisado</button><button className="primary" disabled={busy||!canPublishPlan(assistant,planStatus)} onClick={()=>void publish()}>Publicar</button><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Salvando...':loadedDraft?'Salvar como novo rascunho':'Salvar rascunho'}</button></span></div>}
      </div>
    </div>}
  </section>
}

function PlanAssistant({state,setState,locked}:{state:PlanAssistantState;setState:React.Dispatch<React.SetStateAction<PlanAssistantState>>;locked:boolean}){
  const index=assistantSteps.indexOf(state.currentStep)
  const move=(step:PlanAssistantStep)=>setState(current=>({...current,currentStep:step}))
  const complete=()=>setState(current=>completeAssistantStep(current,current.currentStep))
  return <section className="panel plan-assistant"><header><div><h2>Assistente do plano</h2><small>Etapa atual: {assistantLabels[state.currentStep]}</small></div></header><div className="assistant-steps">{assistantSteps.map(step=><button key={step} className={state.currentStep===step?'active':state.completedSteps.includes(step)?'done':''} disabled={locked} onClick={()=>move(step)}>{assistantLabels[step]}</button>)}</div><label>Objetivo clínico<input value={state.objective} readOnly={locked} onChange={e=>setState(current=>({...current,objective:e.target.value}))} placeholder="Ex.: recomposição corporal com melhora de rotina"/></label>{!locked&&<div className="assistant-actions"><button className="secondary" disabled={index<=0} onClick={()=>move(assistantSteps[index-1])}>Voltar</button><button className="secondary" onClick={complete}>Concluir etapa</button><button className="secondary" disabled={index>=assistantSteps.length-1} onClick={()=>move(assistantSteps[index+1])}>Avançar</button></div>}</section>
}

function Catalog({foods,keys,labels,busy,addFood}:{foods:CatalogFood[];keys:NutrientKey[];labels:Record<NutrientKey,string>;busy:boolean;addFood:(event:FormEvent<HTMLFormElement>)=>Promise<void>}){return <div className="nutrition-grid"><section className="panel"><h2>Novo alimento</h2><p className="muted">Valores por 100 g.</p><form onSubmit={addFood}><label>Nome<input name="name" required minLength={2}/></label><label>Preparo<input name="state" placeholder="Ex.: cozido"/></label><div className="macro-inputs">{keys.map(k=><label key={k}>{labels[k]} ({k==='energyKcal'?'kcal':'g'})<input name={k} type="number" min="0" step="0.01" required/></label>)}</div><button className="primary" disabled={busy}>Cadastrar</button></form></section><section className="panel"><h2>Alimentos da clínica</h2><div className="food-list">{foods.map(f=><article key={f.id}><strong>{f.name}</strong><small>{f.preparationState}</small><div>{f.nutrients.energyKcal} kcal · P {f.nutrients.proteinG} g · C {f.nutrients.carbohydrateG} g · G {f.nutrients.fatG} g</div></article>)}{!foods.length&&<p className="muted">Nenhum alimento próprio.</p>}</div></section></div>}

function MealCard({meal,index,foods,setMeals,addItem,readOnly}:{meal:Meal;index:number;foods:CatalogFood[];setMeals:React.Dispatch<React.SetStateAction<Meal[]>>;addItem:(m:string,f:string,g:number)=>void;readOnly:boolean}){const[food,setFood]=useState(''),[grams,setGrams]=useState(100),total=totalDay([meal]);return <section className="panel meal-editor"><div className="meal-heading"><input aria-label={`Nome da refeição ${index+1}`} value={meal.name} readOnly={readOnly} onChange={e=>setMeals(all=>all.map(m=>m.id===meal.id?{...m,name:e.target.value}:m))}/>{!readOnly&&<button aria-label="Remover refeição" onClick={()=>setMeals(all=>all.filter(m=>m.id!==meal.id))}><Trash2/></button>}</div>{!readOnly&&<div className="add-food-row"><select aria-label="Alimento" value={food} onChange={e=>setFood(e.target.value)}><option value="">Escolha um alimento</option>{foods.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><input aria-label="Gramas" type="number" min=".01" step=".01" value={grams} onChange={e=>setGrams(Number(e.target.value))}/><button className="secondary" onClick={()=>{addItem(meal.id,food,grams);setFood('')}}><Plus/>Item</button></div>}{meal.items.map(item=><div className="meal-item" key={item.id}><span><strong>{item.name}</strong><small>{item.grams} g</small></span>{!readOnly&&<button aria-label={`Remover ${item.name}`} onClick={()=>setMeals(all=>all.map(m=>m.id===meal.id?{...m,items:m.items.filter(i=>i.id!==item.id)}:m))}><Trash2/></button>}</div>)}<div className="meal-subtotal">{total.energyKcal} kcal · P {total.proteinG} g · C {total.carbohydrateG} g · G {total.fatG} g</div></section>}
