import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import type { Session } from '@supabase/supabase-js'
import { Plus, Trash2 } from 'lucide-react'
import { emptyNutrients, totalDay, type Meal, type NutrientKey, type Nutrients } from './lib/nutrition'
import { supabase } from './lib/supabase'

type Patient = { id: string; anonymous_code: string; full_name: string }
type NutrientRow = { id: string; code: string; name: string; unit: string }
type FoodRow = { id: string; name: string; preparation_state: string; food_nutrient_values: { amount_per_100g: number; nutrients: NutrientRow | null }[] }
type CatalogFood = { id: string; name: string; preparationState: string; nutrients: Nutrients }
const aliases: Record<NutrientKey, string[]> = { energyKcal: ['energy_kcal','energy','kcal'], proteinG: ['protein_g','protein'], carbohydrateG: ['carbohydrate_g','carbohydrate','carbs'], fatG: ['fat_g','fat','lipids'], fiberG: ['fiber_g','fiber'], sodiumMg: ['sodium_mg','sodium'], calciumMg: ['calcium_mg','calcium'], ironMg: ['iron_mg','iron'], potassiumMg: ['potassium_mg','potassium'], vitaminCMg: ['vitamin_c_mg','vitamin_c'] }
const keys: NutrientKey[] = ['energyKcal','proteinG','carbohydrateG','fatG']
const labels: Record<NutrientKey,string> = { energyKcal:'Energia',proteinG:'Proteína',carbohydrateG:'Carboidrato',fatG:'Gordura',fiberG:'Fibra',sodiumMg:'Sódio',calciumMg:'Cálcio',ironMg:'Ferro',potassiumMg:'Potássio',vitaminCMg:'Vitamina C' }
function normalize(row: FoodRow): CatalogFood { const nutrients=emptyNutrients(); for(const value of row.food_nutrient_values??[]){const code=value.nutrients?.code.toLowerCase(); const key=(Object.keys(aliases) as NutrientKey[]).find(k=>code&&aliases[k].includes(code)); if(key) nutrients[key]=Number(value.amount_per_100g)} return{id:row.id,name:row.name,preparationState:row.preparation_state,nutrients} }

export function NutritionWorkspace({session,organizationId,patients}:{session:Session;organizationId:string;patients:Patient[]}){
 const [tab,setTab]=useState<'catalog'|'plan'>('catalog'),[foods,setFoods]=useState<CatalogFood[]>([]),[nutrients,setNutrients]=useState<NutrientRow[]>([]),[meals,setMeals]=useState<Meal[]>([{id:crypto.randomUUID(),name:'Café da manhã',items:[]}]),[patientId,setPatientId]=useState(''),[title,setTitle]=useState('Plano alimentar'),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const load=useCallback(async()=>{const [f,n]=await Promise.all([supabase.from('foods').select('id,name,preparation_state,food_nutrient_values(amount_per_100g,nutrients(id,code,name,unit))').eq('organization_id',organizationId).eq('is_active',true).order('name'),supabase.from('nutrients').select('id,code,name,unit').order('sort_order')]); if(f.error||n.error)setMessage(f.error?.message??n.error?.message??'Erro ao carregar catálogo.');else{setFoods(((f.data??[])as unknown as FoodRow[]).map(normalize));setNutrients(n.data??[])}},[organizationId]); useEffect(()=>{void load()},[load]); const totals=useMemo(()=>totalDay(meals),[meals])
 async function addFood(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=event.currentTarget,data=new FormData(form),values=Object.fromEntries(keys.map(k=>[k,Number(String(data.get(k)).replace(',','.'))])) as Record<NutrientKey,number>;if(keys.some(k=>!Number.isFinite(values[k])||values[k]<0)){setBusy(false);return setMessage('Informe valores válidos e não negativos.')}const result=await supabase.from('foods').insert({organization_id:organizationId,name:String(data.get('name')).trim(),preparation_state:String(data.get('state')).trim()||'unspecified',created_by:session.user.id}).select('id').single();if(result.error||!result.data){setBusy(false);return setMessage(result.error?.message??'Falha no cadastro.')}const mapped=keys.map(key=>({key,nutrient:nutrients.find(n=>aliases[key].includes(n.code.toLowerCase()))}));if(mapped.some(x=>!x.nutrient)){await supabase.from('foods').update({is_active:false}).eq('id',result.data.id);setBusy(false);return setMessage('Nutrientes principais ausentes na base. Cadastro revertido.')}const inserted=await supabase.from('food_nutrient_values').insert(mapped.map(x=>({food_id:result.data.id,nutrient_id:x.nutrient!.id,amount_per_100g:values[x.key],data_version:'custom-v1'})));if(inserted.error){await supabase.from('foods').update({is_active:false}).eq('id',result.data.id);setMessage(`Cadastro revertido: ${inserted.error.message}`)}else{form.reset();await load();setMessage('Alimento cadastrado.')}setBusy(false)}
 function addItem(mealId:string,foodId:string,grams:number){const food=foods.find(f=>f.id===foodId);if(!food||grams<=0||!Number.isFinite(grams))return setMessage('Selecione alimento e gramas válidos.');setMeals(all=>all.map(m=>m.id===mealId?{...m,items:[...m.items,{id:crypto.randomUUID(),name:food.name,grams,nutrientsPer100g:food.nutrients}]}:m));setMessage('')}
 async function save(){if(!patientId||!meals.length)return setMessage('Escolha o paciente e inclua uma refeição.');setBusy(true);setMessage('');let planId='';const cleanup:{table:string;id:string}[]=[];try{const p=await supabase.from('plans').insert({organization_id:organizationId,patient_id:patientId,created_by:session.user.id,title:title.trim()||'Plano alimentar',status:'draft'}).select('id').single();if(p.error||!p.data)throw p.error??new Error('Falha no plano');planId=p.data.id;const v=await supabase.from('plan_versions').insert({organization_id:organizationId,plan_id:planId,version_no:1,created_by:session.user.id,change_summary:'Versão inicial'}).select('id').single();if(v.error||!v.data)throw v.error??new Error('Falha na versão');cleanup.push({table:'plan_versions',id:v.data.id});const d=await supabase.from('plan_days').insert({organization_id:organizationId,plan_version_id:v.data.id,day_index:0,label:'Dia 1',kind:'standard'}).select('id').single();if(d.error||!d.data)throw d.error??new Error('Falha no dia');cleanup.push({table:'plan_days',id:d.data.id});for(const [position,meal]of meals.entries()){const m=await supabase.from('meals').insert({organization_id:organizationId,plan_day_id:d.data.id,position,label:meal.name}).select('id').single();if(m.error||!m.data)throw m.error??new Error('Falha na refeição');cleanup.push({table:'meals',id:m.data.id});if(meal.items.length){const items=await supabase.from('meal_items').insert(meal.items.map((item,i)=>({organization_id:organizationId,meal_id:m.data.id,position:i,food_id:foods.find(f=>f.name===item.name)?.id,description:item.name,quantity:item.grams,unit:'g',grams:item.grams,nutrient_snapshot:item.nutrientsPer100g})));if(items.error)throw items.error}}setMessage('Plano salvo como rascunho, versão 1.');setMeals([{id:crypto.randomUUID(),name:'Café da manhã',items:[]}])}catch(error){for(const row of cleanup.reverse())await supabase.from(row.table).delete().eq('id',row.id);if(planId)await supabase.from('plans').update({status:'archived',title:`[Falha revertida] ${title}`}).eq('id',planId);setMessage(`Falha revertida. ${error instanceof Error?error.message:''}`)}finally{setBusy(false)}}
 return <section className="nutrition-workspace"><div className="section-tabs"><button className={tab==='catalog'?'active':''} onClick={()=>setTab('catalog')}>Catálogo próprio</button><button className={tab==='plan'?'active':''} onClick={()=>setTab('plan')}>Editor de plano</button></div>{message&&<div className="notice" role="status">{message}</div>}{tab==='catalog'?<div className="nutrition-grid"><section className="panel"><h2>Novo alimento</h2><p className="muted">Valores por 100 g.</p><form onSubmit={addFood}><label>Nome<input name="name" required minLength={2}/></label><label>Preparo<input name="state" placeholder="Ex.: cozido"/></label><div className="macro-inputs">{keys.map(k=><label key={k}>{labels[k]} ({k==='energyKcal'?'kcal':'g'})<input name={k} type="number" min="0" step="0.01" required/></label>)}</div><button className="primary" disabled={busy}>Cadastrar</button></form></section><section className="panel"><h2>Alimentos da clínica</h2><div className="food-list">{foods.map(f=><article key={f.id}><strong>{f.name}</strong><small>{f.preparationState}</small><div>{f.nutrients.energyKcal} kcal · P {f.nutrients.proteinG} g · C {f.nutrients.carbohydrateG} g · G {f.nutrients.fatG} g</div></article>)}{!foods.length&&<p className="muted">Nenhum alimento próprio.</p>}</div></section></div>:<div className="plan-editor"><section className="panel plan-basics"><label>Paciente<select value={patientId} onChange={e=>setPatientId(e.target.value)}><option value="">Selecione</option>{patients.map(p=><option key={p.id} value={p.id}>{p.anonymous_code} · {p.full_name}</option>)}</select></label><label>Título<input value={title} onChange={e=>setTitle(e.target.value)}/></label></section><section className="live-totals">{keys.map(k=><div key={k}><small>{labels[k]}</small><strong>{totals[k].toLocaleString('pt-BR')} {k==='energyKcal'?'kcal':'g'}</strong></div>)}</section>{meals.map((meal,index)=><MealCard key={meal.id} meal={meal} index={index} foods={foods} setMeals={setMeals} addItem={addItem}/>)}<div className="editor-actions"><button className="secondary" onClick={()=>setMeals(m=>[...m,{id:crypto.randomUUID(),name:`Refeição ${m.length+1}`,items:[]}])}><Plus/>Adicionar refeição</button><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Salvando...':'Salvar rascunho'}</button></div></div>}</section>
}
function MealCard({meal,index,foods,setMeals,addItem}:{meal:Meal;index:number;foods:CatalogFood[];setMeals:React.Dispatch<React.SetStateAction<Meal[]>>;addItem:(m:string,f:string,g:number)=>void}){const[food,setFood]=useState(''),[grams,setGrams]=useState(100),total=totalDay([meal]);return <section className="panel meal-editor"><div className="meal-heading"><input aria-label={`Nome da refeição ${index+1}`} value={meal.name} onChange={e=>setMeals(all=>all.map(m=>m.id===meal.id?{...m,name:e.target.value}:m))}/><button aria-label="Remover refeição" onClick={()=>setMeals(all=>all.filter(m=>m.id!==meal.id))}><Trash2/></button></div><div className="add-food-row"><select aria-label="Alimento" value={food} onChange={e=>setFood(e.target.value)}><option value="">Escolha um alimento</option>{foods.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><input aria-label="Gramas" type="number" min=".01" step=".01" value={grams} onChange={e=>setGrams(Number(e.target.value))}/><button className="secondary" onClick={()=>{addItem(meal.id,food,grams);setFood('')}}><Plus/>Item</button></div>{meal.items.map(item=><div className="meal-item" key={item.id}><span><strong>{item.name}</strong><small>{item.grams} g</small></span><button aria-label={`Remover ${item.name}`} onClick={()=>setMeals(all=>all.map(m=>m.id===meal.id?{...m,items:m.items.filter(i=>i.id!==item.id)}:m))}><Trash2/></button></div>)}<div className="meal-subtotal">{total.energyKcal} kcal · P {total.proteinG} g · C {total.carbohydrateG} g · G {total.fatG} g</div></section>}
