import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { LogOut, RefreshCw, Utensils } from 'lucide-react'
import { supabase } from './lib/supabase'
type PatientAccess={id:string;full_name:string;anonymous_code:string;organization_id:string;professional_id:string}
type Item={id:string;description:string;grams:number;nutrient_snapshot:{food_name?:string;preparation_state?:string}|null}
type Meal={id:string;label:string;position:number;suggested_time:string|null;meal_items:Item[]}
type Day={id:string;label:string;day_index:number;meals:Meal[]}
type Version={id:string;version_no:number;plan_days:Day[]}
type Plan={id:string;title:string;published_at:string|null;plan_versions:Version|null}
type Appointment={id:string;starts_at:string;status:string;modality:string}

export function PatientPortal({patient}:{patient:PatientAccess}){
 const [plans,setPlans]=useState<Plan[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');const [p,a]=await Promise.all([supabase.from('plans').select('id,title,published_at,plan_versions!plans_current_version_tenant_fkey(id,version_no,plan_days(id,label,day_index,meals(id,label,position,suggested_time,meal_items(id,description,grams,nutrient_snapshot))))').eq('patient_id',patient.id).in('status',['published','scheduled']).order('published_at',{ascending:false}),supabase.from('appointments').select('id,starts_at,status,modality').eq('patient_id',patient.id).order('starts_at',{ascending:false})]);const first=p.error??a.error;if(first)setError(`Não foi possível carregar seus dados: ${first.message}`);else{setPlans((p.data??[]) as unknown as Plan[]);setAppointments(a.data??[])}setLoading(false)},[patient.id])
 useEffect(()=>{void load()},[load])
 async function request(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const d=new FormData(event.currentTarget),starts=new Date(String(d.get('starts'))),duration=Number(d.get('duration')),modality=String(d.get('modality')),{data}=await supabase.auth.getSession();if(!data.session)return setError('Sua sessão expirou.');const {error}=await supabase.from('appointments').insert({organization_id:patient.organization_id,patient_id:patient.id,professional_id:patient.professional_id,requested_by:data.session.user.id,status:'requested',modality,starts_at:starts.toISOString(),ends_at:new Date(starts.getTime()+duration*60000).toISOString(),location_text:modality==='in_person'?'Clínica BS':null,patient_note:String(d.get('note'))||null});if(error)setError(error.message);else{event.currentTarget.reset();await load()}}
 return <main className="patient-portal"><header><div className="brand"><span>BS</span><div><strong>BSNutri</strong><small>Meu plano alimentar</small></div></div><button className="secondary" onClick={()=>supabase.auth.signOut()}><LogOut/>Sair</button></header><section className="portal-hero"><small>{patient.anonymous_code}</small><h1>Olá, {patient.full_name.split(' ')[0]}</h1><p>Consulte seu plano, registre sua experiência e solicite consultas.</p></section>{error&&<div className="notice error" role="alert">{error}</div>}<section className="portal-agenda panel"><h2>Solicitar consulta</h2><form onSubmit={request}><label>Data e horário<input name="starts" type="datetime-local" required/></label><div className="field-row"><label>Duração<select name="duration" defaultValue="60"><option value="30">30 min</option><option value="60">60 min</option></select></label><label>Modalidade<select name="modality"><option value="in_person">Presencial</option><option value="online">Online</option><option value="home_visit">Domiciliar</option></select></label></div><label>Observação<input name="note" maxLength={500}/></label><button className="primary">Solicitar horário</button></form>{appointments.map(a=><p className="portal-appointment" key={a.id}><strong>{new Date(a.starts_at).toLocaleString('pt-BR')}</strong><span>{a.status==='requested'?'Aguardando aprovação':a.status==='approved'?'Confirmada':a.status==='rejected'?'Recusada':a.status==='cancelled'?'Cancelada':a.status}</span></p>)}</section>{loading?<div className="portal-empty">Carregando plano...</div>:plans.length?<div className="portal-plans">{plans.map(plan=><PlanCard key={plan.id} plan={plan} patient={patient}/>)}</div>:<div className="portal-empty"><Utensils/><h2>Nenhum plano publicado</h2><p>Quando o profissional publicar seu plano, ele aparecerá aqui.</p><button className="secondary" onClick={()=>void load()}><RefreshCw/>Atualizar</button></div>}</main>
}

function PlanCard({plan,patient}:{plan:Plan;patient:PatientAccess}){const version=plan.plan_versions;return <article className="portal-plan"><header><div><small>Plano vigente</small><h2>{plan.title}</h2></div>{plan.published_at&&<time>Publicado em {new Date(plan.published_at).toLocaleDateString('pt-BR')}</time>}</header>{version?.plan_days?.sort((a,b)=>a.day_index-b.day_index).map(day=><section className="portal-day" key={day.id}><h3>{day.label}</h3>{day.meals.sort((a,b)=>a.position-b.position).map(meal=><article className="portal-meal" key={meal.id}><div><h4>{meal.label}</h4>{meal.suggested_time&&<time>{meal.suggested_time.slice(0,5)}</time>}</div><div><ul>{meal.meal_items.map(item=><li key={item.id}><span><strong>{item.nutrient_snapshot?.food_name??item.description}</strong>{item.nutrient_snapshot?.preparation_state&&<small>{item.nutrient_snapshot.preparation_state}</small>}</span><b>{Number(item.grams).toLocaleString('pt-BR')} g</b></li>)}</ul><MealCheckin meal={meal} versionId={version.id} patient={patient}/></div></article>)}</section>)}</article>}

function MealCheckin({meal,versionId,patient}:{meal:Meal;versionId:string;patient:PatientAccess}){const [message,setMessage]=useState(''),[open,setOpen]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage('');const d=new FormData(event.currentTarget),{data}=await supabase.auth.getSession();if(!data.session)return setMessage('Sessão expirada.');const number=(key:string)=>{const value=String(d.get(key));return value===''?null:Number(value)};const {error}=await supabase.from('meal_checkins').upsert({organization_id:patient.organization_id,patient_id:patient.id,plan_version_id:versionId,meal_id:meal.id,occurred_on:String(d.get('date')),state:String(d.get('state')),hunger_before:number('hunger'),satiety_after:number('satiety'),mood:number('mood'),energy:number('energy'),sleep_quality:number('sleep'),reaction_suspected:d.get('reaction')==='on',symptoms:String(d.get('symptoms'))||null,note:String(d.get('note'))||null,created_by:data.session.user.id},{onConflict:'patient_id,meal_id,occurred_on'});setMessage(error?.message??'Check-in salvo.');if(!error)setOpen(false)}return <div className="meal-checkin"><button className="link" onClick={()=>setOpen(!open)}>{open?'Fechar check-in':'Registrar como foi'}</button>{open&&<form onSubmit={submit}><div className="field-row"><label>Data<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Realização<select name="state"><option value="completed">Realizada</option><option value="adapted">Adaptada</option><option value="skipped">Não realizada</option></select></label></div><div className="checkin-scales">{[['hunger','Fome antes'],['satiety','Saciedade depois'],['mood','Humor'],['energy','Energia'],['sleep','Sono']].map(([name,label])=><label key={name}>{label}<input name={name} type="number" min="0" max="10" placeholder="0–10"/></label>)}</div><label className="check-option"><input name="reaction" type="checkbox"/> Suspeita de reação ou alergia</label><label>Sintomas<input name="symptoms" maxLength={1000}/></label><label>Nota<input name="note" maxLength={1000}/></label><button className="primary">Salvar check-in</button></form>}{message&&<p className="form-message" role="status">{message}</p>}</div>}
